src/main/java/com/phf/vo/Cart.java
package com.phf.vo;

import lombok.Data;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

@Data
public class Cart implements Serializable {
    private Map<Integer, CartItem> items = new HashMap<>();

    public int getSize(){
        return items.size();
    }
    public double getTotalPrice(){
        return items.values().stream().mapToDouble(item->item.getBook().getDprice()*item.getCount()).sum();
    }
    public double getSavePrice(){
        return items.values().stream().mapToDouble(item->(item.getBook().getPrice()-item.getBook().getDprice()) * item.getCount()).sum();
    }
}

src/main/java/com/phf/controller/front/AddressController.java
package com.phf.controller.front;

import com.phf.entity.Address;
import com.phf.entity.User;
import com.phf.service.AddressService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.context.request.SessionScope;

import javax.servlet.http.HttpSession;
import java.util.List;

@Controller
@RequestMapping("front/address")
public class AddressController {
    @Autowired
    private AddressService addressService;

    @RequestMapping("showAddress")
    public String showAddress(Integer userId, Model model){
        List<Address> addresses = addressService.showAddresses(userId);
        model.addAttribute("address",addresses);
        return "forward:/front/order/place-order.jsp";
    }

    @RequestMapping("addAddress")
    public String addAddress(Address address, HttpSession session){
        System.out.println("address = " + address + ", session = " + session);
        User user = (User)session.getAttribute("user");
        address.setUserId(user.getUserId());
        addressService.addAddress(address);

        return "redirect:/front/address/showAddress.do?userId="+user.getUserId();
    }
    @RequestMapping("updateAddress")
    public  String updateAddress(Address address,HttpSession session){
        System.out.println("address = " + address + ", session = " + session);
        User user = (User) session.getAttribute("user");
        address.setUserId(user.getUserId());
        addressService.updateAddress(address);
        return "redirect:/front/address/showAddress.do?userId="+user.getUserId();
    }
    @RequestMapping("removeAddress")
    public String  deleteAddress(Integer id,HttpSession session){
        System.out.println("____________________");
        System.out.println("____________________");
        System.out.println("____________________");
        System.out.println("id = " + id + ", session = " + session);
        User user = (User) session.getAttribute("user");
        addressService.removeAddress(id);
        return "redirect:/front/address/showAddress.do?userId="+user.getUserId();
    }


}

src/main/java/com/phf/controller/front/CartController.java
package com.phf.controller.front;

import com.phf.service.BookService;
import com.phf.vo.Cart;
import com.phf.vo.CartItem;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpSession;
import java.util.Map;

@Controller
@RequestMapping("front/cart")
public class CartController {
    @Autowired
    private BookService bookService;

    @RequestMapping("addCart")
    public String addCart(Integer id, HttpSession session){
        Cart cart = (Cart) session.getAttribute("cart");
        if(cart == null){
            cart = new Cart();
            session.setAttribute("cart",cart);
        }

        Map<Integer, CartItem> items = cart.getItems();
        if(items.containsKey(id)){
            CartItem item = items.get(id);
            item.setCount(item.getCount()+1);
        }else{
            CartItem item = new CartItem();
            item.setCount(1);
            item.setBook(bookService.showOneBook(id));
            items.put(id,item);
        }

        return "redirect:/front/cart/cart.jsp";
    }

    @RequestMapping("increaseCart")
    public String increaseCart(Integer id,HttpSession session){
        Cart cart = (Cart)session.getAttribute("cart");
        Map<Integer, CartItem> items = cart.getItems();
        CartItem item = items.get(id);
        item.setCount(item.getCount()+1);
        return "redirect:/front/cart/cart.jsp";
    }

    @RequestMapping("decreaseCart")
    public String decreaseCart(Integer id,HttpSession session){
        Cart cart = (Cart)session.getAttribute("cart");
        Map<Integer, CartItem> items = cart.getItems();
        CartItem item = items.get(id);
        item.setCount(item.getCount()-1);
        if(item.getCount() <= 0){
            items.remove(id);
        }
        return "redirect:/front/cart/cart.jsp";
    }

    @RequestMapping("removeCart")
    public String removeCart(Integer id,HttpSession session){
        Cart cart = (Cart)session.getAttribute("cart");
        Map<Integer, CartItem> items = cart.getItems();
        items.remove(id);
        return "redirect:/front/cart/cart.jsp";
    }

}

src/main/java/com/phf/controller/front/OrderController.java
package com.phf.controller.front;

import com.phf.entity.Address;
import com.phf.entity.Order;
import com.phf.entity.User;
import com.phf.service.ItemService;
import com.phf.service.OrderService;
import com.phf.vo.Cart;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpSession;
import java.util.Date;

@Controller
@RequestMapping("front/order")
public class OrderController {
    @Autowired
    private OrderService orderService;

    @RequestMapping("addOrder")
    public String addOrder(Order order, HttpSession session) {
        System.out.println("order = " + order);
        User user = (User) session.getAttribute("user");
        order.setUserId(user.getUserId());
        order.setStatus("未支付");
        order.setCreateDate(new Date());

        Cart cart = (Cart) session.getAttribute("cart");
        orderService.addOrder(order, cart.getItems().values());

        cart.getItems().clear();

        return "redirect:/front/order/showOneOrder.do?id=" + order.getOrderId();
    }

    @RequestMapping("showOneOrder")
    public String showOneOrder(Integer id, Model model) {

        Order order = orderService.showOneOrder(id);
        model.addAttribute("order", order);
        return "forward:/front/pay/pay_order.jsp";
    }

    //    @RequestMapping("updateStatus")
//    public String updateStatus(User user){
//        userService.updateUser(user);
//        return "redirect:/back/user/show.do";
//    }
    @RequestMapping("updateOrder")
    public String updateOrder(Order order) {
//        order.setOrderId(order.getOrderId());
//        order.setTotal(order.getTotal());
             order.setStatus("支付成功");
//        order.setName(order.getName());
//        order.setMobile(order.getMobile());
//        order.setProvince(order.getProvince());
//        order.setCity(order.getCity());
//        order.setDistrict(order.getDistrict());
//        order.setTown(order.getTown());
//        order.setAddress(order.getAddress());
//        order.setCreateDate(order.getCreateDate());
//        order.setUserId(order.getUserId());

        orderService.updateOrder(order);
        return"redirect:/front/main.do";
    }
}

src/main/java/com/phf/controller/front/PageController.java
package com.phf.controller.front;


import com.github.pagehelper.PageInfo;
import com.phf.entity.Book;
import com.phf.entity.Category;
import com.phf.service.BookService;
import com.phf.service.CategoryService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

@RequestMapping("front")
@Controller
public class PageController {
@Autowired
    private CategoryService categoryService;
@Autowired
    private BookService bookService;
    @RequestMapping("main")
    public String main(Model model){
        List<Category> categories = categoryService.showCategoriesWithChildren();
        model.addAttribute("categories", categories);

        List<Book> recommendBooks=bookService.showRecommend();
        List<Book> hotSaleBooks=bookService.showHots();
        List<Book> newBooks=bookService.showNewHots();
        List<Book> newHotSaleBooks = bookService.showNewHots();

        model.addAttribute("recommendBooks", recommendBooks);
        model.addAttribute("hotSaleBooks", hotSaleBooks);
        model.addAttribute("newBooks", newBooks);
        model.addAttribute("newHotSaleBooks", newHotSaleBooks);

        return "forward:/front/main.jsp";
    }
@RequestMapping("searchBook")
    public String searchBook(@RequestParam(defaultValue = "1") Integer pageNum,
                             @RequestParam(defaultValue = "5") Integer pageSize,
                             String value,Model model){
    PageInfo<Book> pageInfo=bookService.searchBooks(pageNum,pageSize,value);
    model.addAttribute("pageInfo",pageInfo);
    model.addAttribute("value",value);
    return "forward:/front/search-book.jsp";

    }
    @RequestMapping("showOneBook")
    public String showOneBook(Integer id,Model model){
        Book book= bookService.showOneBook(id);
        model.addAttribute("book",book);
        return"forward:/front/book-detail.jsp";

    }
    @RequestMapping("secondPage")
    public String showSecondPage(@RequestParam(defaultValue = "1") Integer pageNum,
                                 @RequestParam(defaultValue = "5") Integer pageSize,
                                 Integer categoryId,Model model){
        System.out.println("------------------"+categoryId);
        System.out.println("------------------"+categoryId);
        System.out.println("------------------"+categoryId);
        System.out.println("------------------"+categoryId);
        model.addAttribute("categoryId",categoryId);
        PageInfo<Book> pageInfo=bookService.selectSecondBooks(pageNum,pageSize,categoryId);

        model.addAttribute("pageInfo",pageInfo);

        return "forward:/front/search-book.jsp";
    }
}

src/main/java/com/phf/controller/front/UserController.java
package com.phf.controller.front;

import com.phf.entity.User;
import com.phf.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import sun.misc.Request;

import javax.mail.Session;
import javax.servlet.http.HttpSession;
import java.util.Date;

@Controller("frontUserController")
@RequestMapping("front")
public class UserController {
    @Autowired
    private UserService userService;
    @RequestMapping("login")
    public String login(String email, String password, HttpSession session){
        try {
            User user = userService.login(email, password);
            session.setAttribute("user",user);
            return "redirect:/front/main.do";
        }catch(Exception e){
            e.printStackTrace();
            session.setAttribute("msg",e.getMessage());
            return "redirect:/front/login.jsp";
        }

    }
    @RequestMapping("register")
    public String register(User user,String validateCode, HttpSession httpSession) {
        user.setCreateDate(new Date());
        System.out.println("user= " + user + ", validateCode = " + validateCode + ", httpSession = " + httpSession);
        if (!validateCode.equalsIgnoreCase((String) httpSession.getAttribute("realCode"))) {
            httpSession.setAttribute("msg", "验证码错误");
            return "redirect:/front/register.jsp";
        } else {
            userService.addUser(user);
            httpSession.setAttribute("user", user);
            return "redirect:/front/registerOK.jsp";

        }
    }
}

src/main/webapp/front/cart/cart.jsp
<%--
  Created by IntelliJ IDEA.
  User: Xsy
  Date: 2020/7/14
  Time: 22:43
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="${pageContext.request.contextPath}/css/bootstrap.css">
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="${pageContext.request.contextPath}/js/bootstrap.js"></script>
</head>
<body>
<%@ include file="/front/commons/header.jsp"%>
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <img src="${pageContext.request.contextPath}/images/cart/dd_logo.jpg" alt="" class="pull-right">
        </div>
        <div class="col-md-7">

            <ul class="nav nav-pills " style="padding-top:10px">
                <li  style="margin: 10px;background:rgb(255,102,102)"><h4 style="margin:15px;color:rgb(255,231,250)">1.购物车</h4></li>
                <li  style="margin: 10px;background:rgb(246,246,246)"><h4 style="margin:15px" class="text-muted">2.填写订单</h4></li>
                <li  style="margin:10px;background:rgb(246,246,246)"><h4 style="margin:15px" class="text-muted">3.支付订单</h4></li>
            </ul>
            <h4 class="align-right"><a href="${pageContext.request.contextPath}/front/main.do" class="pull-right text-muted">继续浏览</a></h4>
        <br/>
            <br/>


    </div>
    <hr style="border:solid 2px red;">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-sm-12" style="padding-left:150px">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-4">商品信息</div>
                            <div class="col-md-2">单价（元）</div>
                            <div class="col-md-2 text-center">数量</div>
                            <div class="col-md-2">金额（元）</div>
                            <div class="col-md-2">操作</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <ul class="media-list">
                <c:forEach var="e" items="${sessionScope.cart.items}">
                    <div class="media">
                        <div class="media-left media-middle">
                            <img src="${pageContext.request.contextPath}/images/book/${e.value.book.cover}" alt="" class="media-object" style="width:130px">
                        </div>
                        <div class="media-body">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-4">
                                        <span class="text-muted small">${e.value.book.bookName}</span>
                                    </div>
                                    <div class="col-md-2">
                                        <span class="text-muted small">￥${e.value.book.dprice}</span>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="input-group">
                                            <div class="input-group-btn" onclick="location.href='${pageContext.request.contextPath}/front/cart/decreaseCart.do?id=${e.key}'">
                                                <button class="btn btn-default minus" ><span class="glyphicon glyphicon-minus"/></button>
                                            </div>
                                            <input type="hidden" name="id" value="${e.key}">
                                            <input type="text"  class="form-control text-center" name="count" id="" value="${e.value.count}" >
                                            <div class="input-group-btn" onclick="location.href='${pageContext.request.contextPath}/front/cart/increaseCart.do?id=${e.key}'">
                                                <button class="btn btn-default plus" ><span class="glyphicon glyphicon-plus"/></button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <span class="text-muted small text-center">￥${e.value.book.dprice * e.value.count}</span>
                                    </div>
                                    <div class="col-md-2">
                                        <a href="${pageContext.request.contextPath}/front/cart/removeCart.do?id=${e.key}" class="text-muted small">删除</a>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <hr>
                    </div>
                </c:forEach>



            </ul>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-md-2 text-center">
                    <strong class="h4 center-block">店铺合计</strong>
                </div>
                <div class="col-md-3 col-md-offset-7">
                    <div class="row">
                        <div class="col-md-6">
                            <p><span class="small text-muted">总计：</span><span style="color:#ff0000">￥${sessionScope.cart.totalPrice}</span></p>
                            <p class="small text-muted">已节省：<span>￥${sessionScope.cart.savePrice}</span></p>
                        </div>
                        <div class="col-md-6">
                            <a href="${pageContext.request.contextPath}/front/address/showAddress.do?userId=${sessionScope.user.userId}" class="btn btn-danger">结算</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
</script>
</div>
</body>

</html>